name: harvest-tourapi

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'   # 6시간마다(UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      DATA_GO_KR_TOURAPI: ${{ secrets.DATA_GO_KR_TOURAPI }}
      TOUR_LANGS: ko,en,ja,chs,cht
      DAYS_AHEAD: '60'
      AREACODES: '1,2,3,4,5,6,7,8,31,32,33,34,35,36,37,38,39'
      TRANSFORM_LOOKBACK_HOURS: '48'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      # 1) 수확
      - name: harvest festivals
        run: node scripts/harvest-tourapi-festivals.mjs

      - name: harvest attractions
        run: node scripts/harvest-tourapi-attractions.mjs

      - name: harvest food
        run: node scripts/harvest-tourapi-food.mjs

      - name: harvest stay
        run: node scripts/harvest-tourapi-accommodation.mjs

      # 2) 변환 (festival → events) 기존 스크립트
      - name: transform festivals → events
        run: node scripts/transform-events.mjs

      # 3) 변환 (food/stay/attraction → events)
      - name: transform places → events
        run: node scripts/transform-places-to-events.mjs

      # 4) 검증(최근 8h 요약)
      - name: verify recent (8h)
        run: |
          SINCE=$(node -e "const d=new Date();d.setHours(d.getHours()-8);console.log(d.toISOString())")
          curl -s "$SUPABASE_URL/rest/v1/raw_sources?select=dataset,lang,count:count()&fetched_at=gte.$SINCE&group=dataset,lang&order=dataset.asc,lang.asc" \
            -H "apikey: $SUPABASE_SERVICE_ROLE" -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE" | jq .
