name: harvest-tourapi

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      DATA_GO_KR_TOURAPI: ${{ secrets.DATA_GO_KR_TOURAPI }} # 인코딩 키
      TOUR_LANGS: ko,en,ja,chs,cht
      DAYS_AHEAD: "60"
      AREACODES: "1,2,3,4,5,6,7,8,31,32,33,34,35,36,37,38,39"
      TRANSFORM_LOOKBACK_HOURS: "72"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      # 0) TourAPI 키 200 확인
      - name: Sanity | TourAPI key HTTP check
        run: |
          FROM=$(date -u +%Y%m%d)
          TO=$(date -u -d "+30 days" +%Y%m%d)
          URL="https://apis.data.go.kr/B551011/KorService2/searchFestival2?serviceKey=${DATA_GO_KR_TOURAPI}&MobileOS=ETC&MobileApp=HallyuPass&_type=json&eventStartDate=${FROM}&eventEndDate=${TO}&areaCode=1&numOfRows=1&pageNo=1&lang=ko"
          echo "[GET] $URL"
          CODE=$(curl -s -o /tmp/t.json -w "%{http_code}" "$URL")
          head -c 180 /tmp/t.json; echo; echo "HTTP=$CODE"
          test "$CODE" = "200"

      # 1) 수집
      - name: Harvest | festivals
        run: node scripts/harvest-tourapi-festivals.mjs
      - name: Harvest | attractions
        run: node scripts/harvest-tourapi-attractions.mjs
      - name: Harvest | food
        run: node scripts/harvest-tourapi-food.mjs
      - name: Harvest | stay
        run: node scripts/harvest-tourapi-accommodation.mjs

      # 2) 변환
      - name: Transform | festivals → events
        run: node scripts/transform-events.mjs
      - name: Transform | food/stay/attraction → events
        run: node scripts/transform-places-to-events.mjs

      # 3) 적재 확인: 8시간 내 총건수 0이면 실패로 처리
      - name: Verify | raw_sources counts (8h, fail if zero)
        shell: bash
        run: |
          SINCE=$(node -e "const d=new Date();d.setHours(d.getHours()-8);console.log(d.toISOString())")
          RES=$(curl -s "${SUPABASE_URL}/rest/v1/raw_sources?select=count:count()&fetched_at=gte.${SINCE}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE}" -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE}")
          echo "$RES" | jq .
          TOTAL=$(echo "$RES" | jq '.[0].count // 0')
          if [ "${TOTAL:-0}" -lt 1 ]; then
            echo "No TourAPI rows ingested in last 8h."
            exit 1
          fi
