name: harvest
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      DATA_GO_KR_TOURAPI: ${{ secrets.DATA_GO_KR_TOURAPI }}
      DATA_GO_KR_KCISA:  ${{ secrets.DATA_GO_KR_KCISA }}
      TOUR_LANGS: ko,en,ja,chs,cht
      DAYS_AHEAD: 60
      AREACODES: 1,2,3,4,5,6,7,8,31,32,33,34,35,36,37,38,39

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # KCISA 시크릿이 주입됐는지 여부를 먼저 확인하는 스텝
      - name: Sanity check KCISA secret
        env:
          DATA_GO_KR_KCISA: ${{ secrets.DATA_GO_KR_KCISA }}
        run: node -e "const v=process.env.DATA_GO_KR_KCISA||'';console.log({KCISA_set:v.length>0,len:v.length})"

      - name: Print key state
        run: node scripts/print-key-state.mjs

      - name: Debug TourAPI
        run: node scripts/debug-tourapi.mjs

      - name: Debug KCISA
        if: ${{ env.DATA_GO_KR_KCISA != '' }}
        env:
          DATA_GO_KR_KCISA: ${{ secrets.DATA_GO_KR_KCISA }}
        run: node scripts/debug-kcisa.mjs

      - name: Harvest festivals
        run: node scripts/harvest-tourapi-festivals.mjs
