name: harvest-tourapi

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # 6시간마다(UTC)

jobs:
  run:
    name: harvest-tourapi
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      DATA_GO_KR_TOURAPI: ${{ secrets.DATA_GO_KR_TOURAPI }}
      TOUR_LANGS: ko,en,ja,chs,cht
      DAYS_AHEAD: '60'
      AREACODES: '1,2,3,4,5,6,7,8,31,32,33,34,35,36,37,38,39'

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # util.mjs 실제 내용 확인(1회용 진단)
      - name: show util.mjs
        run: |
          ls -la scripts/lib || true
          echo '--- scripts/lib/util.mjs (first 160 lines) ---'
          sed -n '1,160p' scripts/lib/util.mjs || true

      - name: print-key-state
        run: node scripts/print-key-state.mjs

      - name: print-fingerprint
        run: node scripts/print-tourapi-fingerprint.mjs

      - name: debug-tourapi
        run: node scripts/debug-tourapi.mjs
        continue-on-error: true

      # ========= Harvest =========
      - name: harvest-festivals
        run: node scripts/harvest-tourapi-festivals.mjs

      - name: harvest-food
        run: node scripts/harvest-tourapi-food.mjs

      - name: harvest-stay
        run: node scripts/harvest-tourapi-accommodation.mjs

      - name: harvest-course
        run: node scripts/harvest-tourapi-courses.mjs

      # ========= Transform =========
      - name: transform-events
        run: node scripts/transform-events.mjs

      - name: transform-food
        run: node scripts/transform-upsert-food.mjs

- name: show harvest-tourapi-food.mjs header
  run: |
    sed -n '1,25p' scripts/harvest-tourapi-food.mjs
