name: harvest-tourapi
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      DATA_GO_KR_TOURAPI: ${{ secrets.DATA_GO_KR_TOURAPI }} # 인코딩키
      DATA_GO_KR_KEY:     ${{ secrets.DATA_GO_KR_TOURAPI }} # 별칭
      TOUR_LANGS: ko,en              # 임시 축소(레이트리밋 회피). 안정 후 ko,en,ja,chs,cht 복구
      DAYS_AHEAD: "60"
      AREACODES: "1,2,3,4,5,6,7,8,31,32,33,34,35,36,37,38,39"
      TRANSFORM_LOOKBACK_HOURS: "72"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: |
          npm init -y
          npm i @supabase/supabase-js@2

      # --- Debugging step (필요 시만 사용, 평소엔 주석 처리) ---
      - name: print-festivals-head
        run: |
          echo "== head scripts/harvest-tourapi-festivals.mjs =="
          sed -n '1,25p' scripts/harvest-tourapi-festivals.mjs
          echo "== util exports =="
          sed -n '1,60p' scripts/lib/util.mjs

      - name: Harvest | festivals
        run: node scripts/harvest-tourapi-festivals.mjs
      - name: Harvest | attractions
        run: node scripts/harvest-tourapi-attractions.mjs
      - name: Harvest | food
        run: node scripts/harvest-tourapi-food.mjs
      - name: Harvest | stay
        run: node scripts/harvest-tourapi-accommodation.mjs

      - name: Transform | festivals → events
        run: node scripts/transform-events.mjs
      - name: Transform | places → events
        run: node scripts/transform-places-to-events.mjs
