# .github/workflows/harvest-tourapi.yml
# 목적: TourAPI 축제 데이터 수집(raw_sources) → 변환(events)
# 실행: 수동 + 6시간 주기(UTC)

name: harvest-tourapi

on:
  # 수동 실행 버튼 노출
  workflow_dispatch:
  # 스케줄 실행(UTC 기준 6시간마다)
  schedule:
    - cron: "0 */6 * * *"

jobs:
  harvest_tourapi:
    name: harvest-tourapi
    runs-on: ubuntu-latest

    # 전역 환경변수(시크릿 포함). 값은 레포 Settings → Secrets에 등록되어 있어야 함
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      DATA_GO_KR_TOURAPI: ${{ secrets.DATA_GO_KR_TOURAPI }}
      TOUR_LANGS: ko,en,ja,chs,cht
      DAYS_AHEAD: 60
      AREACODES: 1,2,3,4,5,6,7,8,31,32,33,34,35,36,37,38,39

    steps:
      # 1) 코드 체크아웃
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      # 2) Node 설정
      - name: Node 설정
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) TourAPI 키 상태(마스킹) 출력
      - name: TourAPI 키 상태 출력(마스킹)
        run: node scripts/print-key-state.mjs

      # 4) TourAPI 키 지문(앞6/뒤6) 출력
      - name: TourAPI 키 지문 출력
        run: node scripts/print-tourapi-fingerprint.mjs

      # 5) 검색 API 프로빙(실패해도 계속)
      - name: TourAPI 디버그(searchFestival2 점검)
        run: node scripts/debug-tourapi.mjs
        continue-on-error: true

      # 6) 수확: TourAPI → raw_sources
      - name: 수확 실행(TourAPI → raw_sources)
        run: node scripts/harvest-tourapi-festivals.mjs

      # 7) 변환: raw_sources → events
      - name: 변환 실행(raw_sources → events)
        run: node scripts/transform-events.mjs

      # 8) 실패 표시(로그용)
      - name: 실패 표시
        if: failure()
        run: echo "::error:: harvest-tourapi failed"
